#
#      ______
#    \-      -/  ♥
# \_/          \
# |        >  < |
# |_  <  //  ω //
# / \          /
#   /-________-\
#

[[aliases]]
name = "ls"
value = "exa --icons -F -a"

[[aliases]]
name = "lsw"
value = "/bin/ls"

[[aliases]]
name = "la"
value = "ls -laah --icons"

[[aliases]]
name = "py3"
value = "pypy3"

[[aliases]]
name = "brb"
value = "sudo shutdown -r now"

[[aliases]]
name = "clipcopy"
value = "xclip -sel c"

[[aliases]]
name = "lenny"
value = "echo $LENNY | clipcopy"

[[aliases]]
name = "cls"
value = "/usr/bin/clear;/bin/ls -G"

[[aliases]]
name = "uwu"
value = 'uwufetch'

# run commands interactively
[[aliases]]
name = "cp"
value = 'cp -i'
[[aliases]]
name = "mv"
value = 'mv -i'
[[aliases]]
name = "rm"
value = 'rm -I'

[[aliases]]
name = "sh_reload"
value = { zsh = "exec zsh", fish = "exec fish", bash = "exec bash" }

[[aliases]]
name = "cago"
value = "cargo"

[[aliases]]
name = "iforgor"
value = "tldr"
[[aliases]]
name = "matlab"
value = '/Applications/MATLAB_R2021a.app/bin/matlab -nodesktop'
[[aliases]]
name = "eprog"
value = "$HOME/eth/1/prog"
# [[aliases]]
# name = "COLAUX"
# value ="$HOME/eth/1/prog/assignments/colaux"

[[aliases]]
name = "eth"
value = "cd $HOME/eth/5/"

[[aliases]]
name = "battery"
value = 'pmset -g batt | rg -o "\d+%" | cut -d% -f1'

[[aliases]]
name = "cdtemp"
value = "cd $(mktemp -d)"

[[aliases]]
name = "bcurl"
value = "curl -A 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36'"

[[aliases]]
name = "gpgh"
value = 'gpg -u8EDE8162443D32F776B832250C7C069BB9928147 '


[[aliases]]
name = "nvide"
value = "neovide --multigrid "

[[aliases]]
name = "temperature"
value = "istats"
# work="cd ~/dociq/cleanhtml/ && codium . && lazygit"
# # alias work="/Users/hasenmafia/Library/Application\ Support/iTerm2/iterm2env/versions/3.8.6/bin/python3 $HOME/Library/Application\ Support/iTerm2/Scripts/work.py"
#
# docx2html='/Applications/LibreOffice.app/Contents/MacOS/soffice --headless --convert-to html:"HTML" '
[[aliases]]
name = "tt"
value = "taskwarrior-tui"

# # ts-new() {
# #     mkdir "$1" && \
# #     cd "$1" && \
# #     yarn init && \
# #     cp -r ~/dociq/config/{*,.*} . && \
# #     yarn add --dev @types/node @types/jest @typescript-eslint/eslint-plugin @typescript-eslint/parser eslint eslint-config-google eslint-plugin-unicorn jest prettier ts-jest typescript
# #
# # }
#
# sysprog='cd ~/eth/3/sysprog'
[[aliases]]
name = "python3"
value = 'python3.12'
[[aliases]]
name = "ipy"
value = 'ipython'
#
[[aliases]]
name = "nconf"
value = 'nvim ~/.config/nvim/lua/hyde/'

[[aliases]]
name = ":e"
value = 'nvim'

[[aliases]]
name = "l"
value = "ls --group-directories-first -lah"

[[aliases]]
name = "ll"
value = "ls --group-directories-first -laah"

[[aliases]]
name = "lm"
value = "ls -lahgs modified"

[[aliases]]
name = "lmr"
value = "ls -lahgs modified --reverse"

[[aliases]]
name = "goodnight"
value = "echo 'so long and good night' && systemctl suspend"

[[aliases]]
name = "gn"
value = "systemctl suspend"

# make ripgrep search smartly
[[aliases]]
name = "rg"
value = "rg -S"

## git
#

[[aliases]]
name = "ga"
value = "git add"

[[aliases]]
name = "gc"
value = "git commit"

[[aliases]]
name = "gp"
value = "git pull"

[[aliases]]
name = "gP"
value = "git push"

[[aliases]]
name = "icat"
value = "kitty +kitten icat"

[[aliases]]
name = "nfzf"
value = "nvim $(fzf)"

[[aliases]]
name = "sqlite"
value = "sqlite3 -init ~/.config/sqliterc"

[[aliases]]
name = "sqlite3"
value = "sqlite3 -init ~/.config/sqliterc"

[[aliases]]
name = "unicodeit"
value = "python3 -m unicodeit.cli"

[[aliases]]
name = "py"
value = "ptpython --dark-bg"

[[aliases]]
name = "ffox"
value = "/Applications/Firefox Developer Edition.app/Contents/MacOS/firefox-bin"

# g=git
# ga='git add'
# gaa='git add --all'
# gam='git am'
# gama='git am --abort'
# gamc='git am --continue'
# gams='git am --skip'
# gamscp='git am --show-current-patch'
# gap='git apply'
# gapa='git add --patch'
# gapt='git apply --3way'
# gau='git add --update'
# gav='git add --verbose'
# gb='git branch'
# gbD='git branch --delete --force'
# gba='git branch --all'
# gbd='git branch --delete'
# gbda='git branch --no-color --merged | command grep -vE "^([+*]|\s*($(git_main_branch)|$(git_develop_branch))\s*$)" | command xargs git branch --delete 2>/dev/null'
# gbg='git branch -vv | grep ": gone\]"'
# gbgD='local res=$(gbg | awk '\''{print $1}'\'') && [[ $res ]] && echo $res | xargs git branch -D'
# gbgd='local res=$(gbg | awk '\''{print $1}'\'') && [[ $res ]] && echo $res | xargs git branch -d'
# gbl='git blame -b -w'
# gbnm='git branch --no-merged'
# gbr='git branch --remote'
# gbs='git bisect'
# gbsb='git bisect bad'
# gbsg='git bisect good'
# gbsr='git bisect reset'
# gbss='git bisect start'
# gc='git commit --verbose'
# 'gc!'='git commit --verbose --amend'
# gca='git commit --verbose --all'
# 'gca!'='git commit --verbose --all --amend'
# gcam='git commit --all --message'
# 'gcan!'='git commit --verbose --all --no-edit --amend'
# 'gcans!'='git commit --verbose --all --signoff --no-edit --amend'
# gcas='git commit --all --signoff'
# gcasm='git commit --all --signoff --message'
# gcb='git checkout -b'
# gcd='git checkout $(git_develop_branch)'
# gcf='git config --list'
# gcl='git clone --recurse-submodules'
# gclean='git clean --interactive -d'
# gcm='git checkout $(git_main_branch)'
# gcmsg='git commit --message'
# 'gcn!'='git commit --verbose --no-edit --amend'
# gco='git checkout'
# gcor='git checkout --recurse-submodules'
# gcount='git shortlog --summary --numbered'
# gcp='git cherry-pick'
# gcpa='git cherry-pick --abort'
# gcpc='git cherry-pick --continue'
# gcs='git commit --gpg-sign'
# gcsm='git commit --signoff --message'
# gcss='git commit --gpg-sign --signoff'
# gcssm='git commit --gpg-sign --signoff --message'
# gd='git diff'
# gdca='git diff --cached'
# gdct='git describe --tags $(git rev-list --tags --max-count=1)'
# gdcw='git diff --cached --word-diff'
# gds='git diff --staged'
# gdt='git diff-tree --no-commit-id --name-only -r'
# gdup='git diff @{upstream}'
# gdw='git diff --word-diff'
# gf='git fetch'
# gfa='git fetch --all --prune --jobs=10'
# gfg='git ls-files | grep'
# gfo='git fetch origin'
# gg='git gui citool'
# gga='git gui citool --amend'
# ggpull='git pull origin "$(git_current_branch)"'
# ggpur=ggu
# ggpush='git push origin "$(git_current_branch)"'
# ggsup='git branch --set-upstream-to=origin/$(git_current_branch)'
# ghh='git help'
# gignore='git update-index --assume-unchanged'
# gignored='git ls-files -v | grep "^[[:lower:]]"'
# git-svn-dcommit-push='git svn dcommit && git push github $(git_main_branch):svntrunk'
# gk='\gitk --all --branches &!'
# gke='\gitk --all $(git log --walk-reflogs --pretty=%h) &!'
# gl='git pull'
# glg='git log --stat'
# glgg='git log --graph'
# glgga='git log --graph --decorate --all'
# glgm='git log --graph --max-count=10'
# glgp='git log --stat --patch'
# glo='git log --oneline --decorate'
# globurl='noglob urlglobber '
# glod='git log --graph --pretty='\''%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset'\'
# glods='git log --graph --pretty='\''%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset'\'' --date=short'
# glog='git log --oneline --decorate --graph'
# gloga='git log --oneline --decorate --graph --all'
# glol='git log --graph --pretty='\''%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset'\'
# glola='git log --graph --pretty='\''%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset'\'' --all'
# glols='git log --graph --pretty='\''%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset'\'' --stat'
# glp=_git_log_prettily
# gluc='git pull upstream $(git_current_branch)'
# glum='git pull upstream $(git_main_branch)'
# gm='git merge'
# gma='git merge --abort'
# gmom='git merge origin/$(git_main_branch)'
# gmtl='git mergetool --no-prompt'
# gmtlvim='git mergetool --no-prompt --tool=vimdiff'
# gmum='git merge upstream/$(git_main_branch)'
# goodnight='pmset sleepnow'
# gp='git push'
# gpd='git push --dry-run'
# gpf='git push --force-with-lease --force-if-includes'
# 'gpf!'='git push --force'
# gpgh='gpg -u8EDE8162443D32F776B832250C7C069BB9928147 '
# gpoat='git push origin --all && git push origin --tags'
# gpod='git push origin --delete'
# gpr='git pull --rebase'
# gpristine='git reset --hard && git clean --force -dfx'
# gpsup='git push --set-upstream origin $(git_current_branch)'
# gpsupf='git push --set-upstream origin $(git_current_branch) --force-with-lease --force-if-includes'
# gpu='git push upstream'
# gpv='git push --verbose'
# gr='git remote'
# gra='git remote add'
# grb='git rebase'
# grba='git rebase --abort'
# grbc='git rebase --continue'
# grbd='git rebase $(git_develop_branch)'
# grbi='git rebase --interactive'
# grbm='git rebase $(git_main_branch)'
# grbo='git rebase --onto'
# grbom='git rebase origin/$(git_main_branch)'
# grbs='git rebase --skip'
# grep='grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox}'
# grev='git revert'
# grh='git reset'
# grhh='git reset --hard'
# grm='git rm'
# grmc='git rm --cached'
# grmv='git remote rename'
# groh='git reset origin/$(git_current_branch) --hard'
# grrm='git remote remove'
# grs='git restore'
# grset='git remote set-url'
# grss='git restore --source'
# grst='git restore --staged'
# grt='cd "$(git rev-parse --show-toplevel || echo .)"'
# gru='git reset --'
# grup='git remote update'
# grv='git remote --verbose'
# gsb='git status --short --branch'
# gsd='git svn dcommit'
# gsh='git show'
# gsi='git submodule init'
# gsps='git show --pretty=short --show-signature'
# gsr='git svn rebase'
# gss='git status --short'
# gst='git status'
# gsta='git stash push'
# gstaa='git stash apply'
# gstall='git stash --all'
# gstc='git stash clear'
# gstd='git stash drop'
# gstl='git stash list'
# gstp='git stash pop'
# gsts='git stash show --text'
# gstu='gsta --include-untracked'
# gsu='git submodule update'
# gsw='git switch'
# gswc='git switch --create'
# gswd='git switch $(git_develop_branch)'
# gswm='git switch $(git_main_branch)'
# gtl='gtl(){ git tag --sort=-v:refname -n --list "${1}*" }; noglob gtl'
# gts='git tag --sign'
# gtv='git tag | sort -V'
# gunignore='git update-index --no-assume-unchanged'
# gunwip='git log --max-count=1 | grep -q -c "\--wip--" && git reset HEAD~1'
# gup='git pull --rebase'
# gupa='git pull --rebase --autostash'
# gupav='git pull --rebase --autostash --verbose'
# gupom='git pull --rebase origin $(git_main_branch)'
# gupomi='git pull --rebase=interactive origin $(git_main_branch)'
# gupv='git pull --rebase --verbose'
# gwch='git whatchanged -p --abbrev-commit --pretty=medium'
# gwip='git add -A; git rm $(git ls-files --deleted) 2> /dev/null; git commit --no-verify --no-gpg-sign --message "--wip-- [skip ci]"'
